export const US_SERVERS = [
  // Retail Servers
  'Aegwynn',
  'Aerie Peak',
  'Agamaggan',
  'Aggramar',
  'Akama',
  'Alexstrasza',
  'Alleria',
  'Altar of Storms',
  'Alterac Mountains',
  'Aman\'Thul',
  'Andorhal',
  'Anetheron',
  'Antonidas',
  'Anub\'arak',
  'Anvilmar',
  'Arathor',
  'Archimonde',
  'Area 52',
  'Argent Dawn',
  'Arthas',
  'Arygos',
  'Auchindoun',
  'Azgalor',
  'Azjol-Nerub',
  'Azshara',
  'Azuremyst',
  'Baelgun',
  'Balnazzar',
  'Black Dragonflight',
  'Blackhand',
  'Blackrock',
  'Blackwater Raiders',
  'Blackwing Lair',
  'Blade\'s Edge',
  'Bladefist',
  'Bleeding Hollow',
  'Blood Furnace',
  'Bloodhoof',
  'Bloodscalp',
  'Bonechewer',
  'Borean Tundra',
  'Boulderfist',
  'Bronzebeard',
  'Burning Blade',
  'Burning Legion',
  'Caelestrasz',
  'Cairne',
  'Cenarion Circle',
  'Cenarius',
  'Cho\'gall',
  'Chromaggus',
  'Coilfang',
  'Crushridge',
  'Daggerspine',
  'Dalaran',
  'Dalvengyr',
  'Dark Iron',
  'Darkspear',
  'Darrowmere',
  'Dath\'Remar',
  'Dawnbringer',
  'Deathwing',
  'Demon Soul',
  'Dentarg',
  'Destromath',
  'Dethecus',
  'Detheroc',
  'Doomhammer',
  'Draenor',
  'Dragonblight',
  'Dragonmaw',
  'Drak\'thul',
  'Drak\'tharon',
  'Draka',
  'Drenden',
  'Dunemaul',
  'Durotan',
  'Duskwood',
  'Earthen Ring',
  'Echo Isles',
  'Eitrigg',
  'Eldre\'Thalas',
  'Elune',
  'Emerald Dream',
  'Eonar',
  'Eredar',
  'Executus',
  'Exodar',
  'Farstriders',
  'Feathermoon',
  'Fenris',
  'Firetree',
  'Fizzcrank',
  'Frostmane',
  'Frostwolf',
  'Galakrond',
  'Garithos',
  'Garona',
  'Garrosh',
  'Ghostlands',
  'Gilneas',
  'Gnomeregan',
  'Goldrinn',
  'Gorefiend',
  'Gorgonnash',
  'Greymane',
  'Grizzly Hills',
  'Gul\'dan',
  'Gundrak',
  'Gurubashi',
  'Hakkar',
  'Haomarush',
  'Hellscream',
  'Hydraxis',
  'Hyjal',
  'Icecrown',
  'Illidan',
  'Jaedenar',
  'Jubei\'Thos',
  'Kael\'thas',
  'Kalecgos',
  'Kargath',
  'Kel\'Thuzad',
  'Khadgar',
  'Khaz Modan',
  'Khaz\'goroth',
  'Kil\'jaeden',
  'Kilrogg',
  'Kirin Tor',
  'Korgath',
  'Korialstrasz',
  'Kul Tiras',
  'Laughing Skull',
  'Lethon',
  'Lightbringer',
  'Lightning\'s Blade',
  'Lightninghoof',
  'Llane',
  'Lothar',
  'Madoran',
  'Maelstrom',
  'Magtheridon',
  'Maiev',
  'Mal\'Ganis',
  'Malfurion',
  'Malorne',
  'Malygos',
  'Mannoroth',
  'Medivh',
  'Misha',
  'Mok\'Nathal',
  'Moon Guard',
  'Moonrunner',
  'Mug\'thol',
  'Muradin',
  'Nagrand',
  'Nathrezim',
  'Nazgrel',
  'Nazjatar',
  'Ner\'zhul',
  'Nesingwary',
  'Norgannon',
  'Onyxia',
  'Perenolde',
  'Proudmoore',
  'Quel\'dorei',
  'Quel\'Thalas',
  'Ragnaros',
  'Ravencrest',
  'Ravenholdt',
  'Rexxar',
  'Rivendare',
  'Runetotem',
  'Sargeras',
  'Scarlet Crusade',
  'Scilla',
  'Sen\'jin',
  'Sentinels',
  'Shadow Council',
  'Shadowmoon',
  'Shadowsong',
  'Shandris',
  'Shattered Halls',
  'Shattered Hand',
  'Shu\'halo',
  'Silver Hand',
  'Silvermoon',
  'Sisters of Elune',
  'Skullcrusher',
  'Skywall',
  'Smolderthorn',
  'Spinebreaker',
  'Spirestone',
  'Staghelm',
  'Steamwheedle Cartel',
  'Stonemaul',
  'Stormrage',
  'Stormreaver',
  'Stormscale',
  'Suramar',
  'Tanaris',
  'Terenas',
  'Terokkar',
  'Thaurissan',
  'The Forgotten Coast',
  'The Scryers',
  'The Underbog',
  'The Venture Co',
  'Thorium Brotherhood',
  'Thrall',
  'Thunderhorn',
  'Thunderlord',
  'Tichondrius',
  'Tortheldrin',
  'Trollbane',
  'Turalyon',
  'Twisting Nether',
  'Uldaman',
  'Uldum',
  'Undermine',
  'Ursin',
  'Uther',
  'Vashj',
  'Vek\'nilash',
  'Velen',
  'Warsong',
  'Whisperwind',
  'Wildhammer',
  'Windrunner',
  'Winterhoof',
  'Wyrmrest Accord',
  'Ysera',
  'Ysondre',
  'Zangarmarsh',
  'Zul\'jin',
  'Zuluhed',
  // Classic Servers
  'Whitemane',
  'Benediction',
  'Faerlina',
  'Grobbulus',
  'Mankrik',
  'Pagle',
  'Westfall',
  'Windseeker',
  'Atiesh',
  'Azuresong',
  'Bloodsail Buccaneers',
  'Deviate Delight',
  'Earthfury',
  'Heartseeker',
  'Incendius',
  'Kirtonos',
  'Kromcrush',
  'Kurinnaxx',
  'Loatheb',
  'Netherwind',
  'Old Blanchy',
  'Rattlegore',
  'Remulos',
  'Skeram',
  'Smolderweb',
  'Stalagg',
  'Sulfuras',
  'Thalnos',
  'Thunderfury',
  'Yojamba'
];

export const EU_SERVERS = [
  // Retail Servers
  'Aegwynn',
  'Aerie Peak',
  'Agamaggan',
  'Aggramar',
  'Akama',
  'Alexstrasza',
  'Alleria',
  'Alterac Mountains',
  'Aman\'Thul',
  'Andorhal',
  'Anetheron',
  'Antonidas',
  'Anub\'arak',
  'Anvilmar',
  'Arathor',
  'Archimonde',
  'Area 52',
  'Argent Dawn',
  'Arthas',
  'Arygos',
  'Auchindoun',
  'Azjol-Nerub',
  'Azshara',
  'Azuremyst',
  'Baelgun',
  'Balnazzar',
  'Black Dragonflight',
  'Blackhand',
  'Blackrock',
  'Blackwater Raiders',
  'Blackwing Lair',
  'Blade\'s Edge',
  'Bladefist',
  'Bleeding Hollow',
  'Blood Furnace',
  'Bloodhoof',
  'Bloodscalp',
  'Bonechewer',
  'Borean Tundra',
  'Boulderfist',
  'Bronzebeard',
  'Burning Blade',
  'Burning Legion',
  'Caelestrasz',
  'Cairne',
  'Cenarion Circle',
  'Cenarius',
  'Cho\'gall',
  'Chromaggus',
  'Coilfang',
  'Crushridge',
  'Daggerspine',
  'Dalaran',
  'Dalvengyr',
  'Dark Iron',
  'Darkspear',
  'Darrowmere',
  'Dath\'Remar',
  'Dawnbringer',
  'Deathwing',
  'Demon Soul',
  'Dentarg',
  'Destromath',
  'Dethecus',
  'Detheroc',
  'Doomhammer',
  'Draenor',
  'Dragonblight',
  'Dragonmaw',
  'Drak\'thul',
  'Drak\'tharon',
  'Draka',
  'Drenden',
  'Dunemaul',
  'Durotan',
  'Duskwood',
  'Earthen Ring',
  'Echo Isles',
  'Eitrigg',
  'Eldre\'Thalas',
  'Elune',
  'Emerald Dream',
  'Eonar',
  'Eredar',
  'Executus',
  'Exodar',
  'Farstriders',
  'Feathermoon',
  'Fenris',
  'Firetree',
  'Fizzcrank',
  'Frostmane',
  'Frostwolf',
  'Galakrond',
  'Garithos',
  'Garona',
  'Garrosh',
  'Ghostlands',
  'Gilneas',
  'Gnomeregan',
  'Goldrinn',
  'Gorefiend',
  'Gorgonnash',
  'Greymane',
  'Grizzly Hills',
  'Gul\'dan',
  'Gundrak',
  'Gurubashi',
  'Hakkar',
  'Haomarush',
  'Hellscream',
  'Hydraxis',
  'Hyjal',
  'Icecrown',
  'Illidan',
  'Jaedenar',
  'Jubei\'Thos',
  'Kael\'thas',
  'Kalecgos',
  'Kargath',
  'Kel\'Thuzad',
  'Khadgar',
  'Khaz Modan',
  'Khaz\'goroth',
  'Kil\'jaeden',
  'Kilrogg',
  'Kirin Tor',
  'Korgath',
  'Korialstrasz',
  'Kul Tiras',
  'Laughing Skull',
  'Lethon',
  'Lightbringer',
  'Lightning\'s Blade',
  'Lightninghoof',
  'Llane',
  'Lothar',
  'Madoran',
  'Maelstrom',
  'Magtheridon',
  'Maiev',
  'Mal\'Ganis',
  'Malfurion',
  'Malorne',
  'Malygos',
  'Mannoroth',
  'Medivh',
  'Misha',
  'Mok\'Nathal',
  'Moon Guard',
  'Moonrunner',
  'Mug\'thol',
  'Muradin',
  'Nagrand',
  'Nathrezim',
  'Nazgrel',
  'Nazjatar',
  'Ner\'zhul',
  'Nesingwary',
  'Norgannon',
  'Onyxia',
  'Perenolde',
  'Proudmoore',
  'Quel\'dorei',
  'Quel\'Thalas',
  'Ragnaros',
  'Ravencrest',
  'Ravenholdt',
  'Rexxar',
  'Rivendare',
  'Runetotem',
  'Sargeras',
  'Scarlet Crusade',
  'Scilla',
  'Sen\'jin',
  'Sentinels',
  'Shadow Council',
  'Shadowmoon',
  'Shadowsong',
  'Shandris',
  'Shattered Halls',
  'Shattered Hand',
  'Shu\'halo',
  'Silver Hand',
  'Silvermoon',
  'Sisters of Elune',
  'Skullcrusher',
  'Skywall',
  'Smolderthorn',
  'Spinebreaker',
  'Spirestone',
  'Staghelm',
  'Steamwheedle Cartel',
  'Stonemaul',
  'Stormrage',
  'Stormreaver',
  'Stormscale',
  'Suramar',
  'Tanaris',
  'Terenas',
  'Terokkar',
  'Thaurissan',
  'The Forgotten Coast',
  'The Scryers',
  'The Underbog',
  'The Venture Co',
  'Thorium Brotherhood',
  'Thrall',
  'Thunderhorn',
  'Thunderlord',
  'Tichondrius',
  'Tortheldrin',
  'Trollbane',
  'Turalyon',
  'Twisting Nether',
  'Uldaman',
  'Uldum',
  'Undermine',
  'Ursin',
  'Uther',
  'Vashj',
  'Vek\'nilash',
  'Velen',
  'Warsong',
  'Whisperwind',
  'Wildhammer',
  'Windrunner',
  'Winterhoof',
  'Wyrmrest Accord',
  'Ysera',
  'Ysondre',
  'Zangarmarsh',
  'Zul\'jin',
  'Zuluhed',
  // Classic Servers
  'Firemaw',
  'Gehennas',
  'Mograine',
  'Pyrewood Village',
  'Razorgore',
  'Shazzrah',
  'Venoxis',
  'Zandalar Tribe',
  'Ashbringer',
  'Auberdine',
  'Bloodfang',
  'Dragonfang',
  'Earthshaker',
  'Everlook',
  'Finkle',
  'Flamegor',
  'Gandling',
  'Golemagg',
  'Hydraxian Waterlords',
  'Judgement',
  'Lakeshire',
  'Mandokir',
  'Nethergarde Keep',
  'Noggenfogger',
  'Patchwerk',
  'Razorfen',
  'Skullflame',
  'Stonespine',
  'Ten Storms',
  'Transcendence'
]; 